name: Update LeetCode Stats
on:
  schedule:
    - cron: '0 12 * * *'  # Ежедневно в 12:00 UTC
  workflow_dispatch:       # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Права на запись в репозиторий
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests

      - name: Run LeetCode updater
        run: python scripts/update_leetcode.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto: Update LeetCode stats"
          git push
